version: "3"
services:
  backend:
    build: backend
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      - DB_NAME
      - DB_HOST
      - DB_PASSWORD
      - DB_PORT
      - DB_USER
  bot:
    build: bot
    environment:
      - BACKEND_URL=backend:8080
      - DB_NAME
      - DB_HOST
      - DB_PASSWORD
      - DB_PORT
      - DB_USER
      - VK_ACCESS_TOKEN
      - VK_GROUP_ID
    depends_on:
      - backend